<?php require_once dirname(__FILE__).'/crmmsgcs-list.phtml' ?>
<?php require_once dirname(__FILE__).'/crmmsgcs-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/crmmsgcs-messagegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/crmmsgcs-messageform.phtml' ?>
<?php require_once dirname(__FILE__).'/crmmsgcs-txgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/crmmsgcs-txform.phtml' ?>

