<div id="pnl_list">
	<div class="fgta-page-title">Daftar Voucher</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<?php
		$customheadbutton = __DIR__.'/voubatch-list-customheadbutton.phtml'; 
		if (is_file($customheadbutton)) {
			include $customheadbutton;
		} else { ?>
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php } ?>

		<?php
		$customsearch = __DIR__.'/voubatch-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/voubatch-list-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>

			<thead>
				<tr>
					<th mapping="voubatch_id">voubatch_id</th>
					<th mapping="voutype_name">voutype_name</th>
					<th mapping="voubatch_dtend">voubatch_dtend</th>
					<th mapping="voubatch_dtactive">voubatch_dtactive</th>
					<th mapping="voubatch_dtexpired">voubatch_dtexpired</th>
					<th mapping="voumodel_name">voumodel_name</th>
					<th mapping="voubatch_value" style="text-align: right"  formatter="row_format_number">voubatch_value</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Type</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date End</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date Active</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date Expired</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Model</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Value</td>

				</tr>
			</thead>

			<?php } ?>

		</table>
	</div>


	<?php
	$customfootbutton = __DIR__.'/voubatch-list-customfootbutton.phtml'; 
	if (is_file($customfootbutton)) {
		include $customfootbutton;
	} 
	?>	

	<?php
	$custompagefooter = __DIR__.'/voubatch-list-custompagefooter.phtml'; 
	if (is_file($custompagefooter)) {
		include $custompagefooter;
	} 
	?>	

</div>