<thead>
	<tr>
		<th mapping="voubatch_id">voubatch_id</th>
		<th mapping="voubatch_dtexpired">voubatch_dtexpired</th>
		<th mapping="brand_name">brand_name</th>
		<th mapping="voubatch_descr">voubatch_descr</th>
		<th mapping="voubatch_value" style="text-align: right"  formatter="row_format_number">voubatch_value</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Expired</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Brand</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Value</td>
	</tr>
</thead>