<div id="pnl_editqueform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Que</div>
		<a id="pnl_editqueform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editqueform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editqueform-form">

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_voumailerque_id" class="easyui-textbox" mapping="voumailerque_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_voumailerque_email" class="easyui-textbox" mapping="voumailerque_email"  maxlength="60"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_voumailerque_nama" class="easyui-textbox" mapping="voumailerque_nama"  maxlength="60"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Vou Batch</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_voubatch_id" class="easyui-textbox" mapping="voubatch_id"  maxlength="5"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Vou Batch harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Voucher</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_vou_id" class="easyui-textbox" mapping="vou_id"  maxlength="14"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Voucher harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Messaging ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_msg_id" class="easyui-textbox" mapping="msg_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-chk_voumailerque_issend" class="easyui-checkbox c1" mapping="voumailerque_issend" data-options="label: 'Send', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SendBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_voumailerque_sendby" class="easyui-textbox" mapping="voumailerque_sendby"  maxlength="14"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SendDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_voumailerque_senddate" class="easyui-textbox" mapping="voumailerque_senddate"   style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editqueform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Mailer</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editqueform-txt_voumailer_id" class="easyui-textbox" mapping="voumailer_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editqueform-autoadd" type="checkbox"><label for="pnl_editqueform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editqueform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editqueform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editqueform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editqueform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editqueform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
