<div  style="display: flex; justify-content: space-between">
	<div style="display: flex">
		<!-- <a id="pnl_list-btn_download" href="javascript:void(0)" class="easyui-linkbutton" style="margin-right: 50px;">Download Template</a> -->
		<!-- <label style="margin-top: 10px; margin-right: 5px;">Bulan</label> -->
		<!-- <input id="pnl_edit-cbo_month" class="easyui-combo" style="width: 150px;" mapping="hrgrd_id" display="hrgrd_name" data-options="editable:false, valueField:'id', textField:'text'" > -->
		<div id="pnl_list-obj_pastebox" class="pastebox" contenteditable placeholder="Paste data disini..." oninput="if(this.innerHTML.trim()==='<br>')this.innerHTML=''" ></div>
	</div>

	<!-- <a id="pnl_list-btn_kalkulasi" href="javascript:void(0)" class="easyui-linkbutton">Kalkulasi</a> -->
</div>

