<thead>
	<tr>
		<th type="check">chk</th>					
		<th mapping="crmeventmedia_id">crmeventmedia_id</th>
		<th mapping="media_name">media_name</th>
		<th mapping="crmeventmedia_cost" style="text-align: right" formatter="row_format_number">crmeventmedia_cost</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head rowcheck" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Media</td>
		<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Cost</td>
	</tr>
</thead>