<thead>

	<tr>
		<th type="check">chk</th>					
		<th mapping="crmeventpost_id">crmeventpost_id</th>
		<th mapping="crmeventpost_url">crmeventpost_url</th>
		<th mapping="mediaposttype_name">mediaposttype_name</th>
		<th mapping="kol_name">kol_name</th>
		<th mapping="media_name">media_name</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head rowcheck" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">URL</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Post Type</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">KOL</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Media</td>
	</tr>
</thead>