
<thead>
	<tr>
		<th mapping="crmevent_id">crmevent_id</th>
		<th mapping="crmevent_name">crmevent_name</th>
		<th mapping="crmevent_dtstart">crmevent_dtstart</th>
		<th mapping="crmevent_dtend">crmevent_dtend</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Name</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Start</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">End</td>
	</tr>
</thead>