<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}CRM Event{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_id" class="easyui-textbox" mapping="crmevent_id"  maxlength="14" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_name" class="easyui-textbox" mapping="crmevent_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Event harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_descr" class="easyui-textbox" mapping="crmevent_descr"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Start Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_crmevent_dtstart" class="easyui-datebox" style="width: 400px" mapping="crmevent_dtstart" data-options="editable:false , required: true, invalidMessage: 'Tanggal mulai harus diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">End Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_crmevent_dtend" class="easyui-datebox" style="width: 400px" mapping="crmevent_dtend" data-options="editable:false , required: true, invalidMessage: 'Tanggal selesai harus diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Affected Until</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_crmevent_dtaffected" class="easyui-datebox" style="width: 400px" mapping="crmevent_dtaffected" data-options="editable:false , required: true, invalidMessage: 'Batas Tanggal efektif harus diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Message</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_message" class="easyui-textbox" mapping="crmevent_message"  maxlength="1000" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Registered Message</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_registeredmessage" class="easyui-textbox" mapping="crmevent_registeredmessage"  maxlength="1000" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_crmevent_iscommit" class="easyui-checkbox c1" mapping="crmevent_iscommit" data-options="label: 'Commit', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_crmevent_isdisabled" class="easyui-checkbox c1" mapping="crmevent_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_crmevent_isunlimit" class="easyui-checkbox c1" mapping="crmevent_isunlimit" data-options="label: 'Unlimit', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_crmevent_isclose" class="easyui-checkbox c1" mapping="crmevent_isclose" data-options="label: 'Close', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target Invited</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targetinvited" class="easyui-numberbox" mapping="crmevent_targetinvited" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Target Calon Audience yang <b>akan diundang</b>.<br>Untuk ads misalnya IG,FB atau Google, bisa dikosongi.</div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col easyui-tooltip" title="Target Audience yang <b>menghadiri</b> event ini.<br>Untuk digital ads, adalah actual audience yang melakukan telah kontak." style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target Attendant</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targetattendant" class="easyui-numberbox" mapping="crmevent_targetattendant" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target New Contact</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targetnewcontact" class="easyui-numberbox" mapping="crmevent_targetnewcontact" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target Tx</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targettx" class="easyui-numberbox" mapping="crmevent_targettx" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target New Tx</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targettxnew" class="easyui-numberbox" mapping="crmevent_targettxnew" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target Buyer</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targetbuyer" class="easyui-numberbox" mapping="crmevent_targetbuyer" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target Buyer New</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targetbuyernew" class="easyui-numberbox" mapping="crmevent_targetbuyernew" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target Sales</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targetsales" class="easyui-numberbox" mapping="crmevent_targetsales" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Target Sales New</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_targetsalesnew" class="easyui-numberbox" mapping="crmevent_targetsalesnew" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Invited</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totalinvited" class="easyui-numberbox" mapping="crmevent_totalinvited" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Attendant</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totalattendant" class="easyui-numberbox" mapping="crmevent_totalattendant" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total New Contact</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totalnewcontact" class="easyui-numberbox" mapping="crmevent_totalnewcontact" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Tx</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totaltx" class="easyui-numberbox" mapping="crmevent_totaltx" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total New Tx</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totaltxnew" class="easyui-numberbox" mapping="crmevent_totaltxnew" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Buyer</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totalbuyer" class="easyui-numberbox" mapping="crmevent_totalbuyer" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Buyer New</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totalbuyernew" class="easyui-numberbox" mapping="crmevent_totalbuyernew" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Sales</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totalsales" class="easyui-numberbox" mapping="crmevent_totalsales" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Sales New</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_crmevent_totalsalesnew" class="easyui-numberbox" mapping="crmevent_totalsalesnew" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Alokasi Source</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_crmsource_id" class="easyui-combo" style="width: 400px" mapping="crmsource_id" display="crmsource_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: '-- PILIH --'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editinvitedgrid')">
					<div id="pnl_edit-txt_invited_title" class="detilgrid-text">Invited</div>
					<div id="pnl_edit-txt_invited_value" class="detilgrid-value invited_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editattendantgrid')">
					<div id="pnl_edit-txt_attendant_title" class="detilgrid-text">Attendant</div>
					<div id="pnl_edit-txt_attendant_value" class="detilgrid-value attendant_totalvalue">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/crmevent-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

