<div id="pnl_editmediaform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editmediaform-caption">{{STATE_BEG}}Media{{STATE_END}}</div>
		<a id="pnl_editmediaform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editmediaform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editmediaform-form">

		<div class="form_row pnl_editmediaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmediaform-txt_crmeventmedia_id" class="easyui-textbox" mapping="crmeventmedia_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmediaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Media</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmediaform-cbo_media_id" class="easyui-combo" style="width: 400px" mapping="media_id" display="media_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Media harus diisi'"  validType="requiredcombo['pnl_editmediaform-cbo_media_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmediaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Cost</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmediaform-txt_crmeventmedia_cost" class="easyui-numberbox" mapping="crmeventmedia_cost" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmediaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Notes</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmediaform-txt_crmeventmedia_notes" class="easyui-textbox" mapping="crmeventmedia_notes"  maxlength="1000"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row pnl_editmediaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">File</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmediaform-fl_crmeventmedia_file" class="easyui-filebox" mapping="crmeventmedia_file" style="width: 400px" data-options="multiline: false , accept: '*' ">
				<div style="display: flex;">
					<a class="filedownloadlink" id="pnl_editmediaform-fl_crmeventmedia_file_link" style="cursor:pointer; margin-right: 10px; display: none">Download File</a>	
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
				<img id="pnl_editmediaform-fl_crmeventmedia_file_img" style="width: 200px; width: 200px; border: 1px solid: #ccc; display:none">				
			</div>
		</div>

		<div class="form_row pnl_editmediaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Event</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmediaform-txt_crmevent_id" class="easyui-textbox" mapping="crmevent_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editmediaform-autoadd" type="checkbox"><label for="pnl_editmediaform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editmediaform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/crmevent-mediaform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editmediaform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editmediaform-buttonbar-left">
			<a id="pnl_editmediaform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editmediaform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editmediaform-buttonbar-middle">
			<a id="pnl_editmediaform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editmediaform-buttonbar-right">
			<a id="pnl_editmediaform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
