<script>
	window.$fgta.showaccount = false;
</script>



<!-- email dan nama perusahaan -->
<?php require_once dirname(__FILE__).'/register-form-1.phtml' ?>

<!-- konfirmasi kode email -->
<?php require_once dirname(__FILE__).'/register-form-2.phtml' ?>

<!-- masukkan password, -->
<?php require_once dirname(__FILE__).'/register-form-3.phtml' ?>
<!-- sukses dari sini sudah bisa login -->



<?php require_once dirname(__FILE__).'/register-success.phtml' ?>




