<?php $name=$this->BeginForm('pnl_success', 'Success') ?>

	<div>
		Langkah awal registrasi berhasil.<br>
		Selanjutnya silakan <a href="index.php/module/crm/eclient/login">login</a> untuk melengkapi profile anda.<br>
		Profile yang tidak lengkap tidak akan diapprove.<br><br>
		
		Klik <a href="index.php/module/crm/eclient/login" style="font-weight: bold">disini</a>, apabila dalam beberapa detik, halaman belum berpindah ke halaman login.<br>
		
	</div>



<?php $this->EndForm() ?>