<div id="pnl_editaddressform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Address</div>
		<a id="pnl_editaddressform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editaddressform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editaddressform-form">

		<div class="form_row pnl_editaddressform_row txt_custaddress_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaddressform-txt_custaddress_id" class="easyui-textbox" mapping="custaddress_id" uppercase="true" maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaddressform_row txt_custaddress_line1" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Address</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaddressform-txt_custaddress_line1" class="easyui-textbox" mapping="custaddress_line1"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaddressform_row txt_custaddress_line2" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaddressform-txt_custaddress_line2" class="easyui-textbox" mapping="custaddress_line2"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaddressform_row txt_custaddress_line3" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaddressform-txt_custaddress_line3" class="easyui-textbox" mapping="custaddress_line3"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaddressform_row txt_custaddress_city" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaddressform-txt_custaddress_city" class="easyui-textbox" mapping="custaddress_city"  maxlength="60"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaddressform_row txt_custaddress_prov" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Prov</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaddressform-txt_custaddress_prov" class="easyui-textbox" mapping="custaddress_prov"  maxlength="60"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaddressform_row txt_custaddress_postcode" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PostCode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaddressform-txt_custaddress_postcode" class="easyui-textbox" mapping="custaddress_postcode"  maxlength="20"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaddressform_row txt_cust_id" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Customer</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaddressform-txt_cust_id" class="easyui-textbox" mapping="cust_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editaddressform-autoadd" type="checkbox"><label for="pnl_editaddressform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editaddressform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editaddressform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editaddressform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editaddressform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editaddressform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
