<div id="pnl_editcontactform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Contact</div>
		<a id="pnl_editcontactform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editcontactform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editcontactform-form">

		<div class="form_row pnl_editcontactform_row txt_custcontact_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_custcontact_id" class="easyui-textbox" mapping="custcontact_id" uppercase="true" maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row txt_custcontact_data" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Data</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_custcontact_data" class="easyui-textbox" mapping="custcontact_data" uppercase="true" maxlength="60"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row chk_custcontact_isemail" >
			<div class="form_label_col">Contact Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-chk_custcontact_isemail" class="easyui-checkbox c1" mapping="custcontact_isemail" data-options="label: 'Email', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row chk_custcontact_isphone" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-chk_custcontact_isphone" class="easyui-checkbox c1" mapping="custcontact_isphone" data-options="label: 'Phone Number', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row chk_custcontact_iswhatsapp" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-chk_custcontact_iswhatsapp" class="easyui-checkbox c1" mapping="custcontact_iswhatsapp" data-options="label: 'Whatsapp', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row txt_cust_id" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Customer</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_cust_id" class="easyui-textbox" mapping="cust_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editcontactform-autoadd" type="checkbox"><label for="pnl_editcontactform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editcontactform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editcontactform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editcontactform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editcontactform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editcontactform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
