<!-- ini blank phtml -->
<div id="pnl_editupload">
	<div class="fgta-page-title">Upload</div>
	<div>
	Upload data customer
	</div>

	<div style="display: flex; justify-content: space-between">
		<div style="display: flex">
			<div id="pnl_editupload-obj_pastebox" class="pastebox" contenteditable placeholder="Paste template disini..." oninput="if(this.innerHTML.trim()==='<br>')this.innerHTML=''" ></div>
			<div id="pnl_editupload-obj_pastewait" style="padding-top: 10px; padding-left: 10px; display: none">wait....</div>
		</div>
		<a id="pnl_editupload-btn_download" href="javascript:void(0)" class="easyui-linkbutton" style="margin-right: 50px;">Download Template</a>
	</div>

</div>	
