<?php require_once dirname(__FILE__).'/cust-list.phtml' ?>
<?php require_once dirname(__FILE__).'/cust-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/cust-upload.phtml' ?>
<?php require_once dirname(__FILE__).'/cust-contactgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/cust-contactform.phtml' ?>
<?php require_once dirname(__FILE__).'/cust-addressgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/cust-addressform.phtml' ?>



