<div id="pnl_edittargetform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Target Customer</div>
		<a id="pnl_edittargetform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_edittargetform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_edittargetform-form">

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_id" class="easyui-textbox" mapping="broadcastmsgcust_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_name" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_name" class="easyui-textbox" mapping="broadcastmsgcust_name"  maxlength="60"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Name harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_data" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Data</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_data" class="easyui-textbox" mapping="broadcastmsgcust_data"  maxlength="60"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Data harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row chk_broadcastmsgcust_isnew" >
			<div class="form_label_col">Status</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-chk_broadcastmsgcust_isnew" class="easyui-checkbox c1" mapping="broadcastmsgcust_isnew" data-options="label: 'New Customer', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row chk_broadcastmsgcust_isrecvoffer" >
			<div class="form_label_col">Offer</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-chk_broadcastmsgcust_isrecvoffer" class="easyui-checkbox c1" mapping="broadcastmsgcust_isrecvoffer" data-options="label: 'Allow Receive Offer', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_reasonrejectoffer" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reject Reason</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_reasonrejectoffer" class="easyui-textbox" mapping="broadcastmsgcust_reasonrejectoffer"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<?=$this->Section('Variable', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_var1" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Variable 1</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_var1" class="easyui-textbox" mapping="broadcastmsgcust_var1"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_var2" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Variable 2</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_var2" class="easyui-textbox" mapping="broadcastmsgcust_var2"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_var3" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Variable 3</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_var3" class="easyui-textbox" mapping="broadcastmsgcust_var3"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_var4" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Variable 4</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_var4" class="easyui-textbox" mapping="broadcastmsgcust_var4"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_var5" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Variable 5</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_var5" class="easyui-textbox" mapping="broadcastmsgcust_var5"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Result', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edittargetform_row chk_broadcastmsgcust_isfail" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-chk_broadcastmsgcust_isfail" class="easyui-checkbox c1" mapping="broadcastmsgcust_isfail" data-options="label: 'Fail', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edittargetform_row txt_broadcastmsgcust_failreason" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reason</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsgcust_failreason" class="easyui-textbox" mapping="broadcastmsgcust_failreason"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<div class="form_row pnl_edittargetform_row txt_broadcastmsg_id" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edittargetform-txt_broadcastmsg_id" class="easyui-textbox" mapping="broadcastmsg_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_edittargetform-autoadd" type="checkbox"><label for="pnl_edittargetform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_edittargetform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_edittargetform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_edittargetform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_edittargetform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_edittargetform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
