<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Broadcast Type</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row txt_broadcastmsg_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_id" class="easyui-textbox" mapping="broadcastmsg_id"  maxlength="14" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_broadcasttype_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_broadcasttype_id" class="easyui-combo" style="width: 400px" mapping="broadcasttype_id" display="broadcasttype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Type harus diisi'"   validType="requiredcombo['pnl_edit-cbo_broadcasttype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row dt_broadcastmsg_dtstart" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date Start</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_broadcastmsg_dtstart" class="easyui-datebox" style="width: 400px" mapping="broadcastmsg_dtstart" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_descr" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_descr" class="easyui-textbox" mapping="broadcastmsg_descr"  maxlength="255" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Descr harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_template" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Template</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_template" class="easyui-textbox" mapping="broadcastmsg_template"  maxlength="1000" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Template harus diisi', multiline: true, height: '200px' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row pnl_edit_row fl_broadcastmsg_file" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Image</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-fl_broadcastmsg_file" class="easyui-filebox" mapping="broadcastmsg_file" style="width: 400px" data-options="multiline: false , accept: 'image/*' ">
				<div style="display: flex;">
					<a class="filedownloadlink" id="pnl_edit-fl_broadcastmsg_file_link" style="cursor:pointer; margin-right: 10px; display: none">Download File</a>	
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
				<img id="pnl_edit-fl_broadcastmsg_file_img" style="width: 200px; width: 200px; border: 1px solid: #ccc; display:none">				
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_user_dept_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">User Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_user_dept_id" class="easyui-combo" style="width: 400px" mapping="user_dept_id" display="user_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen User harus diisi'"   validType="requiredcombo['pnl_edit-cbo_user_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_unit_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_unit_id" class="easyui-combo" style="width: 400px" mapping="unit_id" display="unit_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<?=$this->Section('Budget', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row cbo_project_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_project_id" class="easyui-combo" style="width: 400px" mapping="project_id" display="project_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_projecttask_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project Task</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projecttask_id" class="easyui-combo" style="width: 400px" mapping="projecttask_id" display="projecttask_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_projbudget_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projbudget_id" class="easyui-combo" style="width: 400px" mapping="projbudget_id" display="projbudget_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_projbudgettask_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget Task</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projbudgettask_id" class="easyui-combo" style="width: 400px" mapping="projbudgettask_id" display="projbudgettask_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_broadcastmsg_isunbudgetted" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_broadcastmsg_isunbudgetted" class="easyui-checkbox c1" mapping="broadcastmsg_isunbudgetted" data-options="label: 'UnBudgetted', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		</div>
					
		<?=$this->Section('Cost', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row txt_broadcasttype_costpermessage" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Cost per Message</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcasttype_costpermessage" class="easyui-numberbox" mapping="broadcasttype_costpermessage" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcasttype_creditpermessage" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Credit per Message</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcasttype_creditpermessage" class="easyui-numberbox" mapping="broadcasttype_creditpermessage" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_custcount" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Cust Count</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_custcount" class="easyui-numberbox" mapping="broadcastmsg_custcount" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_rejectcount" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rejected</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_rejectcount" class="easyui-numberbox" mapping="broadcastmsg_rejectcount" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_sendcount" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To be Send</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_sendcount" class="easyui-numberbox" mapping="broadcastmsg_sendcount" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_totalcost" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Cost</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_totalcost" class="easyui-numberbox" mapping="broadcastmsg_totalcost" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_totalcredit" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Credit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_totalcredit" class="easyui-numberbox" mapping="broadcastmsg_totalcredit" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Execution', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row cbo_broadcastquota_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Quota Used</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_broadcastquota_id" class="easyui-combo" style="width: 400px" mapping="broadcastquota_id" display="broadcastquota_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_partner_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner/Operator</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partner_id" class="easyui-combo" style="width: 400px" mapping="partner_id" display="partner_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_empl_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Process By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_empl_id" class="easyui-combo" style="width: 400px" mapping="empl_id" display="empl_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_custcountdelv" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Delivered</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_custcountdelv" class="easyui-numberbox" mapping="broadcastmsg_custcountdelv" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_delvpercent" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">% Delivered</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_delvpercent" class="easyui-numberbox" mapping="broadcastmsg_delvpercent" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Accounts', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row cbo_cost_accbudget_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Cost Budget Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_cost_accbudget_id" class="easyui-combo" style="width: 400px" mapping="cost_accbudget_id" display="cost_accbudget_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_cost_coa_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Cost Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_cost_coa_id" class="easyui-combo" style="width: 400px" mapping="cost_coa_id" display="cost_coa_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_prepaid_accbudget_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Prepaid Budget Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_prepaid_accbudget_id" class="easyui-combo" style="width: 400px" mapping="prepaid_accbudget_id" display="prepaid_accbudget_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_prepaid_coa_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Prepaid Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_prepaid_coa_id" class="easyui-combo" style="width: 400px" mapping="prepaid_coa_id" display="prepaid_coa_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Other Information', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row cbo_broadcastmodel_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_broadcastmodel_id" class="easyui-combo" style="width: 400px" mapping="broadcastmodel_id" display="broadcastmodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Model harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_broadcastmodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_process_dept_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Process Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_process_dept_id" class="easyui-combo" style="width: 400px" mapping="process_dept_id" display="process_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen User harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_process_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_doc_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_doc_id" class="easyui-combo" style="width: 400px" mapping="doc_id" display="doc_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'ID harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_doc_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Status', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row txt_broadcastmsg_version" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc Version</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_version" class="easyui-numberbox" mapping="broadcastmsg_version" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_broadcastmsg_iscommit" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_broadcastmsg_iscommit" class="easyui-checkbox c1" mapping="broadcastmsg_iscommit" data-options="label: 'Commit', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_commitby" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_commitby" class="easyui-textbox" mapping="broadcastmsg_commitby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_commitdate" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_commitdate" class="easyui-textbox" mapping="broadcastmsg_commitdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_broadcastmsg_isapprovalprogress" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_broadcastmsg_isapprovalprogress" class="easyui-checkbox c1" mapping="broadcastmsg_isapprovalprogress" data-options="label: 'Progress', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_broadcastmsg_isapproved" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_broadcastmsg_isapproved" class="easyui-checkbox c1" mapping="broadcastmsg_isapproved" data-options="label: 'Approved', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_approveby" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_approveby" class="easyui-textbox" mapping="broadcastmsg_approveby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_approvedate" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_approvedate" class="easyui-textbox" mapping="broadcastmsg_approvedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_broadcastmsg_isdeclined" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_broadcastmsg_isdeclined" class="easyui-checkbox c1" mapping="broadcastmsg_isdeclined" data-options="label: 'Declined', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_declineby" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_declineby" class="easyui-textbox" mapping="broadcastmsg_declineby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_declinedate" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_declinedate" class="easyui-textbox" mapping="broadcastmsg_declinedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_broadcastmsg_isexecute" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_broadcastmsg_isexecute" class="easyui-checkbox c1" mapping="broadcastmsg_isexecute" data-options="label: 'Executed', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_executeby" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Executed By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_executeby" class="easyui-textbox" mapping="broadcastmsg_executeby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_broadcastmsg_executedate" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Executed Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_broadcastmsg_executedate" class="easyui-textbox" mapping="broadcastmsg_executedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; ; display:none" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editupload')">
					<div id="pnl_edit-txt_upload_title" class="detilgrid-text">Upload</div>
					<div id="pnl_edit-txt_upload_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_edittargetgrid')">
					<div id="pnl_edit-txt_target_title" class="detilgrid-text">Target Customer</div>
					<div id="pnl_edit-txt_target_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editresultgrid')">
					<div id="pnl_edit-txt_result_title" class="detilgrid-text">Result</div>
					<div id="pnl_edit-txt_result_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editfilesgrid')">
					<div id="pnl_edit-txt_files_title" class="detilgrid-text">Files</div>
					<div id="pnl_edit-txt_files_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editapprovalgrid')">
					<div id="pnl_edit-txt_approval_title" class="detilgrid-text">Approval</div>
					<div id="pnl_edit-txt_approval_value" class="detilgrid-value">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
			<a id="pnl_edit-btn_print" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'icon-print'">print</a>
			
			<a id="pnl_edit-btn_commit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-commit'">Commit</a>			
			<a id="pnl_edit-btn_uncommit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-uncommit'">UnCommit</a>
			
			
				<a id="pnl_edit-btn_approve" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="plain:true,iconCls:'fgta-icon-posting'">Approve</a>
				<a id="pnl_edit-btn_decline" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="plain:true,iconCls:'fgta-icon-unposting'">Decline</a>
				
			
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

